/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzle;

import java.applet.AudioClip;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

import juego.sonido;
import menu_juegos.menu_juegos;

/**
 *
 * @author JHPAT
 */
public class puzzle extends javax.swing.JFrame {

    public puzzle() {
        
        initComponents();
           setLocationRelativeTo(null);
     
     a9.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        a1 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        a4 = new javax.swing.JButton();
        a5 = new javax.swing.JButton();
        a6 = new javax.swing.JButton();
        a7 = new javax.swing.JButton();
        a8 = new javax.swing.JButton();
        a9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        a1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/p1.jpg"))); // NOI18N
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        jPanel1.add(a1);

        a2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/p2.jpg"))); // NOI18N
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        jPanel1.add(a2);

        a3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/p3.jpg"))); // NOI18N
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        jPanel1.add(a3);

        a4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/p4.jpg"))); // NOI18N
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        jPanel1.add(a4);

        a5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/p5.jpg"))); // NOI18N
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        jPanel1.add(a5);

        a6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/p6.jpg"))); // NOI18N
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        jPanel1.add(a6);

        a7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/p7.jpg"))); // NOI18N
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a7ActionPerformed(evt);
            }
        });
        jPanel1.add(a7);

        a8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/p8.jpg"))); // NOI18N
        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a8ActionPerformed(evt);
            }
        });
        jPanel1.add(a8);

        a9.setText("9");
        a9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a9ActionPerformed(evt);
            }
        });
        jPanel1.add(a9);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(340, 0, 700, 700);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alea100.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setOpaque(true);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alea2100.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 190, 100, 70);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rinicio10087.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.setOpaque(true);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reinicio2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 180, 100, 87);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reg.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 10, 200, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tumblr_mynxzy1agC1r6j7rho1_500.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1000, 10, 380, 690);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corab.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 330, 330, 360);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -5, 1430, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
      if(a2.isVisible()==false){
          a2.setText(a1.getText());
          a2.setIcon(a1.getIcon());
          a1.setVisible(false);
          a2.setVisible(true);}
    if(a4.isVisible()==false){
          a4.setText(a1.getText());
          a4.setIcon(a1.getIcon());
          a1.setVisible(false);
          a4.setVisible(true);}
    }//GEN-LAST:event_a1ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
  if(a2.isVisible()==false){
          a2.setText(a5.getText());
          a2.setIcon(a5.getIcon());
          a5.setVisible(false);
          a2.setVisible(true);}
  if(a4.isVisible()==false){
          a4.setText(a5.getText());
          a4.setIcon(a5.getIcon());
          a5.setVisible(false);
          a4.setVisible(true);}
  if(a6.isVisible()==false){
          a6.setText(a5.getText());
          a6.setIcon(a5.getIcon());
          a5.setVisible(false);
          a6.setVisible(true);}
  if(a8.isVisible()==false){
          a8.setText(a5.getText());
          a8.setIcon(a5.getIcon());
          a5.setVisible(false);
          a8.setVisible(true);}
    }//GEN-LAST:event_a5ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
    if(a9.isVisible()==false){
          a9.setText(a6.getText());
          a9.setIcon(a6.getIcon());
          a6.setVisible(false);
          a9.setVisible(true);}
    if(a3.isVisible()==false){
          a3.setText(a6.getText());
          a3.setIcon(a6.getIcon());
          a6.setVisible(false);
          a3.setVisible(true);}
    
      if(a5.isVisible()==false){
          a5.setText(a6.getText());
          a5.setIcon(a6.getIcon());
          a6.setVisible(false);
          a5.setVisible(true);}
    
    
    
    }//GEN-LAST:event_a6ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
 if(a2.isVisible()==false){
          a2.setText(a3.getText());
          a2.setIcon(a3.getIcon());
          a3.setVisible(false);
          a2.setVisible(true);}
   if(a6.isVisible()==false){
          a6.setText(a3.getText());
          a6.setIcon(a3.getIcon());
          a3.setVisible(false);
          a6.setVisible(true);}
   
    }//GEN-LAST:event_a3ActionPerformed

    private void a7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a7ActionPerformed
if(a4.isVisible()==false){
          a4.setText(a7.getText());
          a4.setIcon(a7.getIcon());
          a7.setVisible(false);
          a4.setVisible(true);}    
if(a8.isVisible()==false){
          a8.setText(a7.getText());
          a8.setIcon(a7.getIcon());
          a7.setVisible(false);
          a8.setVisible(true);}  
    }//GEN-LAST:event_a7ActionPerformed

    private void a8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a8ActionPerformed
if(a7.isVisible()==false){
          a7.setText(a8.getText());
          a7.setIcon(a8.getIcon());
          a8.setVisible(false);
          a7.setVisible(true);}   
if(a5.isVisible()==false){
          a5.setText(a8.getText());
          a5.setIcon(a8.getIcon());
          a8.setVisible(false);
          a5.setVisible(true);}  
if(a9.isVisible()==false){
          a9.setText(a8.getText());
          a9.setIcon(a8.getIcon());
          a8.setVisible(false);
          a9.setVisible(true);}  // TODO add your handling code here:
    }//GEN-LAST:event_a8ActionPerformed

    private void a9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a9ActionPerformed
     if(a6.isVisible()==false){
          a6.setText(a9.getText());
          a6.setIcon(a9.getIcon());
          a9.setVisible(false);
          a6.setVisible(true);}
       if(a8.isVisible()==false){
          a8.setText(a9.getText());
          a8.setIcon(a9.getIcon());
          a9.setVisible(false);
          a8.setVisible(true);}
    
    }//GEN-LAST:event_a9ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
         if(a1.isVisible()==false){
          a1.setText(a2.getText());
          a1.setIcon(a2.getIcon());
          a2.setVisible(false);
          a1.setVisible(true);}
             if(a3.isVisible()==false){
          a3.setText(a2.getText());
          a3.setIcon(a2.getIcon());
          a2.setVisible(false);
          a3.setVisible(true);}
             if(a5.isVisible()==false){
          a5.setText(a2.getText());
          a5.setIcon(a2.getIcon());
          a2.setVisible(false);
          a5.setVisible(true);}
    }//GEN-LAST:event_a2ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        if(a5.isVisible()==false){
          a5.setText(a4.getText());
          a5.setIcon(a4.getIcon());
          a4.setVisible(false);
          a5.setVisible(true);}
          if(a1.isVisible()==false){
          a1.setText(a4.getText());
          a1.setIcon(a4.getIcon());
          a4.setVisible(false);
          a1.setVisible(true);}
            if(a7.isVisible()==false){
          a7.setText(a4.getText());
          a7.setIcon(a4.getIcon());
          a4.setVisible(false);
          a7.setVisible(true);}
    }//GEN-LAST:event_a4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 ImageIcon i1 = new  ImageIcon(getClass().getResource("imagen/p1.jpg"));
 ImageIcon i2 = new  ImageIcon(getClass().getResource("imagen/p2.jpg"));
 ImageIcon i3 = new  ImageIcon(getClass().getResource("imagen/p3.jpg"));
 ImageIcon i4 = new  ImageIcon(getClass().getResource("imagen/p4.jpg"));
 ImageIcon i5 = new  ImageIcon(getClass().getResource("imagen/p5.jpg"));
 ImageIcon i6 = new  ImageIcon(getClass().getResource("imagen/p6.jpg"));
 ImageIcon i7 = new  ImageIcon(getClass().getResource("imagen/p7.jpg"));
 ImageIcon i8 = new  ImageIcon(getClass().getResource("imagen/p8.jpg"));  
 
 
  int numero = (int) (Math.random() * 4)+1;
      
      switch(numero){ 
          
          case 1: 
            
            
              
              a1.setIcon(i6);
              a2.setIcon(i3);
              a3.setIcon(i1);
              a4.setIcon(i4);
              a5.setIcon(i8);
              a6.setIcon(i2);
              a7.setIcon(i7);
              a8.setIcon(i5);
              a9.setIcon(i1);
              
              break;
          
          case 2:
            
              
              a1.setIcon(i4);
              a2.setIcon(i1);
              a3.setIcon(i6);
              a4.setIcon(i2);
              a5.setIcon(i8);      
              a6.setIcon(i3);
              a7.setIcon(i7);
              a8.setIcon(i5);
              a9.setIcon(i3);
             
              break;
           case 3:
                   
              
              a1.setIcon(i4);
              a2.setIcon(i1);
              a3.setIcon(i3);
              a4.setIcon(i8);
              a5.setIcon(i2);      
              a6.setIcon(i6);
              a7.setIcon(i7);
              a8.setIcon(i5);
              a9.setIcon(i1);
              
              break;
              case 4:
             
         
              a1.setIcon(i4);
              a2.setIcon(i1);
              a3.setIcon(i3);
              a4.setIcon(i2);
              a5.setIcon(i6);      
              a6.setIcon(i8);
              a7.setIcon(i7);
              a8.setIcon(i5);
              a9.setIcon(i1);
       
              break;
          
          
        
              
      } 
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     ImageIcon i1 = new  ImageIcon(getClass().getResource("imagen/p1.jpg"));
 ImageIcon i2 = new  ImageIcon(getClass().getResource("imagen/p2.jpg"));
 ImageIcon i3 = new  ImageIcon(getClass().getResource("imagen/p3.jpg"));
 ImageIcon i4 = new  ImageIcon(getClass().getResource("imagen/p4.jpg"));
 ImageIcon i5 = new  ImageIcon(getClass().getResource("imagen/p5.jpg"));
 ImageIcon i6 = new  ImageIcon(getClass().getResource("imagen/p6.jpg"));
 ImageIcon i7 = new  ImageIcon(getClass().getResource("imagen/p7.jpg"));
 ImageIcon i8 = new  ImageIcon(getClass().getResource("imagen/p8.jpg"));  
   a1.setIcon(i1);
              a2.setIcon(i2);
              a3.setIcon(i3);
              a4.setIcon(i4);
              a5.setIcon(i5);
              a6.setIcon(i6);
              a7.setIcon(i7);
              a8.setIcon(i8);
              a9.setIcon(i1);
              
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


        menu_juegos x1=new menu_juegos();
   x1.setVisible(true);
  x1.setExtendedState(JFrame.MAXIMIZED_BOTH);  
dispose();


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new puzzle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton a4;
    private javax.swing.JButton a5;
    private javax.swing.JButton a6;
    private javax.swing.JButton a7;
    private javax.swing.JButton a8;
    private javax.swing.JButton a9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
